Repository Re-Spring/DoFront, pull requests merged in 2024-03, with the labels that each got.

#10 [Feature] 메인 홈 상단 메뉴바 구현
  public/images/banner.png
  src/components/common/Footer.js
  src/components/common/Header.js
  src/pages/fairytale/Main.js
  src/styles/common/common.css
  src/styles/mains/footer.css
  src/styles/mains/header.css
  src/styles/mains/main.css
Labels: ⚙️ Feature

#11 [Feature] 🤖챗봇prompt
  .env
  package-lock.json
  public/favicon.ico
  public/index.html
  src/components/common/Chatbot.js
  src/styles/chatbots/Chatbot.css
Labels: ⚙️ Feature

#12 [Feature] 회원가입 완성, 로그인 진행중
  src/apis/authAPI.js
  src/modules/AuthModule.js
  src/pages/user/enroll.js
  src/pages/user/login.js
Labels: ⚙️ Feature

#13 [Feature] 메인 홈 수정 중
  src/components/common/Header.js
  src/styles/mains/footer.css
  src/styles/mains/header.css
Labels: ⚙️ Feature

#16 [Feature] 메인 페이지 동화 리스트 구현 중
  src/apis/StoryAPI.js
  src/components/auth/a/uthAction.js
  src/modules/StoryModule.js
  src/pages/fairytale/Main.js
  src/styles/mains/main.css
Labels: ⚙️ Feature

#19 [Refactoring] 네이밍컨벤션
  src/components/auth/a/uthAction.js
  src/components/auth/authContext.js
  src/pages/fairytale/Main.js
  src/pages/fairytale/Make.js
  src/pages/fairytale/dubing.js
  src/pages/user/enroll.js
  src/pages/user/enroll0.js
  src/pages/user/findId.js
  src/pages/user/findPw.js
  src/pages/user/login.js
  src/styles/chatbots/Chatbot.css
  src/styles/common/common.css
  src/styles/mains/footer.css
  src/styles/mains/header.css
  src/styles/mains/main.css
Labels: 🐞 bug

#20 [Refactoring] 네이밍 컨벤션
  src/components/auth/AuthAction.js
  src/components/auth/AuthContext.js
  src/pages/fairytale/Dubing.js
  src/pages/fairytale/Main.js
  src/pages/fairytale/Make.js
  src/pages/user/Enroll.js
  src/pages/user/Enroll0.js
  src/pages/user/FindId.js
  src/pages/user/FindPw.js
  src/pages/user/Login.js
  src/styles/chatbots/Chatbot.css
  src/styles/common/Common.css
  src/styles/mains/Footer.css
  src/styles/mains/Header.css
  src/styles/mains/Main.css
Labels: 🐞 bug, duplicate

#21 [Refactoring] import 파일 네이밍컨벤션
  package.json
  src/App.js
  src/components/common/Footer.js
  src/components/common/Header.js
  src/pages/fairytale/Main.js
  src/pages/user/Enroll.js
Labels: Refactoring

#22 [Feature] 로그인/로그아웃 구현
  package-lock.json
  package.json
  src/apis/AuthAPI.js
  src/components/common/Header.js
Labels: ⚙️ Feature

#24 [Feature] voice Clone 페이지 추가, 동화 생성 페이지 수정
  src/App.js
  src/apis/CloneAPI.js
  src/apis/MakeAPI.js
  src/pages/clone/Clone.js
  src/pages/fairytale/Make.js
Labels: ⚙️ Feature

#25 [Feature] Navigate 추가
  .env
  src/App.js
  src/apis/DeelpAPI.js
  src/components/common/Nav.js
  src/layouts/Layout.js
  src/modules/DeelpModule.js
  src/pages/fairytale/Deelp.js
  src/pages/user/Enroll.js
Labels: ⚙️ Feature

#27 [Bug] 로그인 후 헤더 변경 수정중
  src/components/common/Header.js
  src/pages/clone/Clone.js
Labels: 🐞 bug

#29 [Feature] 동화 리스트 카테고리 구현
  public/images/fairy10.jpg
  public/images/fairy11.jpg
  public/images/fairy12.jpg
  public/images/fairy13.jpg
  public/images/fairy14.jpg
  public/images/fairy15.jpg
  public/images/fairy16.jpg
  public/images/fairy17.jpg
  public/images/fairy18.jpg
  public/images/fairy19.jpg
  public/images/fairy20.jpg
  public/images/fairy8.jpg
  public/images/fairy9.jpg
  src/pages/fairytale/Main.js
  src/pages/fairytale/Make.js
  src/styles/mains/Main.css
Labels: ⚙️ Feature

#30 [BugFix] 로그인 후 기능 관련 수정
  src/App.js
  src/apis/AuthAPI.js
  src/components/auth/AuthContext.js
  src/components/auth/AuthContext0.js
  src/components/common/Header.js
  src/pages/user/Enroll.js
  src/pages/user/Login.js
Labels: 🐞 bug

#31 [BugFix & Feature] 로그인 상태 전역 관리
  src/App.js
  src/apis/AuthAPI.js
  src/components/auth/AuthContext.js
  src/components/auth/AuthPath.js
  src/components/common/Header.js
Labels: 🐞 bug, ⚙️ Feature

#32 [Feature] 동화 생성 페이지 및 동화 상세 페이지 구현 중
  public/images/fairy21.jpg
  src/App.js
  src/pages/fairytale/BookContent.js
  src/pages/fairytale/Main.js
  src/pages/fairytale/Make.js
  src/pages/mypage/Info.js
  src/styles/mains/BookContent.css
  src/styles/mains/Header.css
  src/styles/mybook/Make.css
Labels: ⚙️ Feature

#34 [Feature] 동화 상세 페이지 구현 중
  src/pages/fairytale/BookContent.js
  src/pages/fairytale/Main.js
  src/styles/mains/BookContent.css
  src/styles/mains/Header.css
Labels: ⚙️ Feature

#35 [Feature] 동화 상세 페이지 구현 중
  src/App.js
  src/pages/fairytale/BookContent.js
  src/styles/mains/BookContent.css
  src/styles/mains/Footer.css
  src/styles/mains/Header.css
  src/styles/mains/Main.css
Labels: ⚙️ Feature

#36 [Feature] 아이디, 비밀번호 찾기 구현
  src/apis/AuthAPI.js
  src/modules/AuthModule.js
  src/pages/user/FindId.js
  src/pages/user/FindPw.js
Labels: ⚙️ Feature

#37 [Feature] 메인페이지 화면구성
  src/apis/MakeAPI.js
  src/apis/StoryAPI.js
  src/apis/VoiceAPI.js
  src/apis/authAPI0.js
  src/pages/fairytale/Main.js
Labels: ⚙️ Feature

#38 [Feature] 동화 상세 페이지 구현 중
  src/App.js
  src/pages/fairytale/BookContent.js
  src/pages/fairytale/Main.js
  src/styles/mains/BookContent.css
Labels: ⚙️ Feature

#39 [Feature] voiceCloning 녹음 세션저장
  .idea/.gitignore
  .idea/DoFront.iml
  .idea/jpa-buddy.xml
  .idea/misc.xml
  src/App.js
  src/apis/VoiceAPI.js
  src/pages/voiceCloning/Voice.js
Labels: ⚙️ Feature

#42 [Feature] 내 정보 수정 기능 완료
  src/components/auth/AuthContext.js
  src/pages/mypage/Info.js
Labels: ⚙️ Feature

#43 [Feature] 백엔드와의 웹 소켓 연결 기능 추가
  package-lock.json
  package.json
  src/apis/MakeAPI.js
  src/pages/fairytale/Make.js
  src/pages/fairytale/WebSocketProvider.js
Labels: ⚙️ Feature

#44 [Feature] voiceClone 리액트 수정
  public/images/clone_img.jpg
  src/apis/VoiceAPI.js
  src/components/auth/AuthContext.js
  src/components/auth/AuthPath.js
  src/modules/VoiceModule.js
  src/pages/user/Enroll.js
  src/pages/voiceCloning/Voice.js
  src/styles/voice/Voice.css
Labels: ⚙️ Feature

#45 [Feature] SearchPage
  src/App.js
  src/components/common/Header.js
  src/pages/fairytale/SearchPage.js
  src/styles/mains/SearchPage.css
Labels: ⚙️ Feature

#46 [Feature] 챗봇 기능 구현 중
  src/components/common/Chatbot.js
  src/pages/fairytale/BookContent.js
  src/styles/mains/BookContent.css
Labels: ⚙️ Feature

#47 [css 수정본]
  src/styles/mains/SearchPage.css
Labels: ⚙️ Feature

#49 [BugFix, Feature] 보이스클론 모듈 연결 성공, 이후 상태 업데이트
  src/apis/VoiceAPI.js
  src/components/auth/AuthContext.js
  src/components/common/Header.js
  src/pages/voiceCloning/Voice.js
Labels: ⚙️ Feature

#51 [Feature] 내 동화 구현 및 회원 탈퇴 구현 중
  src/App.js
  src/components/auth/AuthContext.js
  src/components/common/Chatbot.js
  src/components/common/Header.js
  src/layouts/Layout.js
  src/pages/fairytale/MyBook.js
  src/pages/mypage/Info.js
  src/styles/chatbots/Chatbot.css
  src/styles/mybook/MyBook.css
  src/styles/mypage/Info.css
Labels: ⚙️ Feature

#52 [Feature] 로그인 만료-1
  src/App.js
  src/apis/AuthAPI.js
  src/components/auth/AuthAction.js
  src/components/auth/AuthContext.js
  src/components/auth/SessionTimeout.js
  src/components/common/Header.js
  src/pages/user/Login.js
Labels: ⚙️ Feature

#53 [Feature] 회원 탈퇴 메시지창 수정 및 동화 리스트 더보기, 카테고리 수정 및 메인메뉴 수정
  src/pages/fairytale/Main.js
  src/pages/mypage/Info.js
  src/pages/voiceCloning/Voice.js
  src/styles/mains/Header.css
  src/styles/mains/Main.css
  src/styles/mypage/Info.css
Labels: ⚙️ Feature

#54 [Feature] 웹 소켓 기능 제거 및 Firebase config 파일 생성
  package-lock.json
  package.json
  src/apis/MakeAPI.js
  src/config/Firebase.js
  src/pages/fairytale/Make.js
Labels: ⚙️ Feature

#55 [Refactoring] 로그인 만료-2, css 수정
  public/images/clone_img_3.jpg
  src/apis/AuthAPI.js
  src/components/auth/AuthAction.js
  src/components/auth/AuthContext.js
  src/components/auth/SessionTimeout.js
  src/components/common/Header.js
  src/pages/voiceCloning/Voice.js
  src/styles/voice/Voice.css
Labels: ⚙️ Feature

#56 [Feature] 내 동화 페이지 구현 중
  src/pages/fairytale/MyBook.js
  src/styles/mybook/MyBook.css
Labels: ⚙️ Feature

#57 [Feature] Firebase 메시지 기능 구현 중
  .env
  .gitignore
  src/App.js
  src/components/token/TokenContext.js
  src/config/Firebase.js
  src/configs/Firebase.js
  src/configs/FirebaseConfig.js
  src/pages/fairytale/Make.js
Labels: ⚙️ Feature

#58 [Feature] 탈퇴 회원 기간 만료 후 정보 삭제, 보이스 클론 ux 수정
  public/images/clone_loading.gif
  src/App.js
  src/apis/AdminAPI.js
  src/apis/AuthAPI.js
  src/apis/VoiceAPI.js
  src/apis/authAPI0.js
  src/components/auth/AuthAction.js
  src/components/auth/AuthContext0.js
  src/components/common/Header.js
  src/modules/AdminModule.js
  src/pages/admin/UserInfo.js
  src/pages/user/Enroll0.js
  src/pages/user/FindPw.js
  src/pages/voiceCloning/Voice.js
  src/styles/user/Enroll.css
  src/styles/voice/Voice.css
Labels: ⚙️ Feature, 🔥Refactoring

#59 [Feature] 탈퇴 회원 기간 만료 후 정보 삭제 - 2
  src/App.js
  src/Store.js
  src/pages/admin/UserInfo.js
Labels: ⚙️ Feature

#60 [Feature] 내 동화 페이지 구현 중
  src/pages/fairytale/MyBook.js
Labels: ⚙️ Feature

#61 [Feature] 게시판 구현 중
  .env
  src/App.js
  src/components/common/Header.js
  src/pages/fairytale/SearchPage.js
  src/pages/mypage/CustomerService.js
  src/pages/mypage/CustomerServicePosts.js
  src/styles/mains/SearchPage.css
  src/styles/mypage/CustomerService.css
  src/styles/mypage/CustomerServicePosts.css
Labels: ⚙️ Feature

#63 [Feature] dockerfile add
  Dockerfile
Labels: ⚙️ Feature

#64 [Feature] 내 동화 페이지 구현 완료
  .env
  src/components/common/Header.js
  src/pages/fairytale/MyBook.js
  src/styles/mains/Main.css
  src/styles/mybook/MyBook.css
Labels: ⚙️ Feature

#66 [Feature] 게시판 수정중
  src/App.js
  src/components/common/Header.js
  src/pages/mypage/CustomerService.js
  src/pages/mypage/CustomerServicePosts.js
Labels: ⚙️ Feature

#67 [Refectoring] 동화 생성 필수 요소 추가
  src/pages/fairytale/Make.js
Labels: 🔥Refactoring

#68 [Feature] 메인 동화 리스트 나누기 완료
  src/pages/fairytale/BookContent.js
  src/pages/fairytale/Main.js
  src/pages/fairytale/MyBook.js
  src/pages/mypage/Info.js
  src/styles/mains/Main.css
  src/styles/mybook/MyBook.css
  src/styles/mypage/Info.css
Labels: ⚙️ Feature

#70 [Refactoring] 헤더 UI 수정, 탈퇴 회원 데이터 관리 UI 수정 + API 수정
  src/apis/AdminAPI.js
  src/components/common/Header.js
  src/modules/AdminModule.js
  src/pages/admin/UserInfo.js
  src/styles/admin/admin.css
  src/styles/mains/Header.css
  src/styles/voice/Voice.css
Labels: 🔥Refactoring

#69 [Feature] 배포를위해 build 작업 및 IP주소 변경
  .env
  Dockerfile
  nginx.conf
  package-lock.json
  package.json
  src/apis/AdminAPI.js
  src/apis/AuthAPI.js
  src/apis/MakeAPI.js
  src/apis/StoryAPI.js
  src/apis/VoiceAPI.js
Labels: ⚙️ Feature

#77 [Refactoring] print, console 지움
  src/pages/fairytale/BookContent.js
  src/pages/fairytale/Main.js
  src/pages/fairytale/MyBook.js
Labels: 🔥Refactoring

#79 [Refactoring] console.log 제거
  src/App.js
  src/apis/AdminAPI.js
  src/apis/AuthAPI.js
  src/apis/VoiceAPI.js
  src/components/auth/AuthContext.js
  src/components/auth/SessionTimeout.js
  src/pages/admin/UserInfo.js
  src/pages/mypage/CustomerService.js
  src/pages/mypage/CustomerServicePostDetail.js
  src/pages/mypage/CustomerServicePosts.js
  src/pages/mypage/Info.js
  src/pages/user/Enroll.js
  src/pages/user/Login.js
  src/pages/voiceCloning/Voice.js
Labels: 🔥Refactoring

#80 [Refactoring] 문의하기 수정
  src/pages/mypage/CustomerService.js
  src/pages/mypage/CustomerServicePostDetail.js
  src/pages/mypage/CustomerServicePosts.js
  src/styles/admin/admin.css
  src/styles/mypage/CustomerService.css
  src/styles/mypage/CustomerServicePostDetail.css
  src/styles/mypage/CustomerServicePosts.css
Labels: 🔥Refactoring
